
DROP TABLE PRODUCT;
DROP TABLE CATEGORY;



CREATE TABLE IF NOT EXISTS CATEGORY(
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    description VARCHAR(300),
    price INTEGER,
    image_url VARCHAR(300),
    category_id INTEGER,
    PRIMARY KEY(id),
    FOREIGN KEY (category_id)  REFERENCES category(id)
);
